services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: AplikacjaWaluty123
      POSTGRES_DB: waluty
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: waluty_backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:AplikacjaWaluty123@db/waluty
    ports:
      - "8001:8001"

volumes:
  postgres_data: